### ISSUE TITLE
Observable compatibility

### ISSUE THREAD

**Issue by backspaces** [backspaces/as-app3d#33]
Three heroes of the JS revolution have created _Observable_
> Observable: https://beta.observablehq.com/
> Forum: https://talk.observablehq.com/

This issue is to make asx and as-core be Observable-friendly.

The immediate issues are:
- Convert our `<script>` src to be UMD rather than a simple IIFE. I've already started on that.
- For dependencies, possibly roll them up into a bundle. Only asx has dependencies currently.
- Create npm repos for all our work. Observable uses unpkg to get dependencies etc.

To understand the deep npm fu required, unpkg can actually create modules for you given a complete npm package that has all the correct metadata. "Bare" modules for example. This definitely is non-trivial. Spend an hour reading d3's beautiful build strategy to grok it.

So npm is a big deal for us (Redfish/Simtable). We're working on a strategy for that, stay tuned.

**Comment by backspaces** [comment]
UMD, btw, is helpful because it can be required() by node, and used in a browser `<script>` tag. This is particularly useful for testing.

Here is a notebook using both require() on a umd, and an import on a module (as-core):
https://beta.observablehq.com/@backspaces/agentscript-test-es6-module-import-and-umd-require

**Comment by sdwfrost** [comment]
Thanks @backspaces for making AgentScript Observable-friendly; do you have an example that employs as-app3d?

**Comment by backspaces** [comment]
Sorry to be late but traveling in Italy w/o laptop. Will respond more fully in 4 weeks! App3d repo has examples but we’ve refactored so much that it is obsolete. Instead we’re making a kit of parts of an extreme diversity: workers, M/V split, 2d, 3d, controls etc. we’ll then provide a few roll ups like app3d
